<a href="https://colab.research.google.com/github/shankar1108/python-project/blob/main/Pandras.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
arr=np.arange(2,11).reshape (3,3)
print (arr)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [ ]:
a=np.arange(10,100,10).reshape(3,3)
print(a)

[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [ ]:
a=a[-1]
print(a)

90


In [ ]:
L=range(1000)
%timeit np.power(L,2)

124 µs ± 60.4 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [ ]:
import pandas as pd
list1=['Python','Maths','Data','Science','Ml']
series=pd.Series(list1)
series

0     Python
1      Maths
2       Data
3    Science
4         Ml
dtype: object

In [ ]:
series[1:2]

1    Maths
dtype: object

In [ ]:
data=pd.read_csv('/content/IPL_Squad_2023_Auction_Dataset (1).csv')
data

Unnamed: 0      Player's List Base Price          TYPE  COST IN ₹ (CR.)  \
0             0        Shivam Mavi    4000000        BOWLER              6.0   
1             1      Joshua Little    5000000        BOWLER              4.4   
2             2    Kane Williamson   20000000       BATSMAN              2.0   
3             3        K.S. Bharat    2000000  WICKETKEEPER              1.2   
4             4       Mohit Sharma    5000000        BOWLER              0.5   
..          ...                ...        ...           ...              ...   
563         563        Dhruv Patel    2000000   ALL-ROUNDER              NaN   
564         564    Jack Prestwidge    2000000   ALL-ROUNDER              NaN   
565         565     Aditya Sarvate    2000000   ALL-ROUNDER              NaN   
566         566      Sagar Solanki    2000000   ALL-ROUNDER              NaN   
567         567  Prenelan Subrayen    2000000   ALL-ROUNDER              NaN   

     Cost IN $ (000) 2022 Squad            Team  
0              720.0        KKR  Gujarat Titans  
1              528.0        NaN  Gujarat Titans  
2              240.0        SRH  Gujarat Titans  
3              144.0         DC  Gujarat Titans  
4               60.0        NaN  Gujarat Titans  
..               ...        ...             ...  
563              NaN        NaN          Unsold  
564              NaN        NaN          Unsold  
565              NaN        NaN          Unsold  
566              NaN        NaN          Unsold  
567              NaN        NaN          Unsold  

[568 rows x 8 columns]

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 568 entries, 0 to 567
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   Unnamed: 0       568 non-null    int64  
 1   Player's List    568 non-null    object 
 2   Base Price       568 non-null    object 
 3   TYPE             568 non-null    object 
 4   COST IN ₹ (CR.)  243 non-null    float64
 5   Cost IN $ (000)  243 non-null    float64
 6   2022 Squad       230 non-null    object 
 7   Team             568 non-null    object 
dtypes: float64(2), int64(1), object(5)
memory usage: 35.6+ KB


In [ ]:
data.tail()

Unnamed: 0      Player's List Base Price         TYPE  COST IN ₹ (CR.)  \
563         563        Dhruv Patel    2000000  ALL-ROUNDER              NaN   
564         564    Jack Prestwidge    2000000  ALL-ROUNDER              NaN   
565         565     Aditya Sarvate    2000000  ALL-ROUNDER              NaN   
566         566      Sagar Solanki    2000000  ALL-ROUNDER              NaN   
567         567  Prenelan Subrayen    2000000  ALL-ROUNDER              NaN   

     Cost IN $ (000) 2022 Squad    Team  
563              NaN        NaN  Unsold  
564              NaN        NaN  Unsold  
565              NaN        NaN  Unsold  
566              NaN        NaN  Unsold  
567              NaN        NaN  Unsold

In [ ]:
data.head()

Unnamed: 0    Player's List Base Price          TYPE  COST IN ₹ (CR.)  \
0           0      Shivam Mavi    4000000        BOWLER              6.0   
1           1    Joshua Little    5000000        BOWLER              4.4   
2           2  Kane Williamson   20000000       BATSMAN              2.0   
3           3      K.S. Bharat    2000000  WICKETKEEPER              1.2   
4           4     Mohit Sharma    5000000        BOWLER              0.5   

   Cost IN $ (000) 2022 Squad            Team  
0            720.0        KKR  Gujarat Titans  
1            528.0        NaN  Gujarat Titans  
2            240.0        SRH  Gujarat Titans  
3            144.0         DC  Gujarat Titans  
4             60.0        NaN  Gujarat Titans

In [ ]:
data.isnull().sum()

Unnamed: 0           0
Player's List        0
Base Price           0
TYPE                 0
COST IN ₹ (CR.)    325
Cost IN $ (000)    325
2022 Squad         338
Team                 0
dtype: int64

In [ ]:
data.isnull()

Unnamed: 0  Player's List  Base Price   TYPE  COST IN ₹ (CR.)  \
0         False          False       False  False            False   
1         False          False       False  False            False   
2         False          False       False  False            False   
3         False          False       False  False            False   
4         False          False       False  False            False   
..          ...            ...         ...    ...              ...   
563       False          False       False  False             True   
564       False          False       False  False             True   
565       False          False       False  False             True   
566       False          False       False  False             True   
567       False          False       False  False             True   

     Cost IN $ (000)  2022 Squad   Team  
0              False       False  False  
1              False        True  False  
2              False       False  False  
3              False       False  False  
4              False        True  False  
..               ...         ...    ...  
563             True        True  False  
564             True        True  False  
565             True        True  False  
566             True        True  False  
567             True        True  False  

[568 rows x 8 columns]

In [ ]:
data.isnull().sum().sum()

988

In [ ]:
data.shape

(568, 8)

In [ ]:
data.duplicated().sum()

0

In [ ]:
data['TYPE']

0            BOWLER
1            BOWLER
2           BATSMAN
3      WICKETKEEPER
4            BOWLER
           ...     
563     ALL-ROUNDER
564     ALL-ROUNDER
565     ALL-ROUNDER
566     ALL-ROUNDER
567     ALL-ROUNDER
Name: TYPE, Length: 568, dtype: object

In [ ]:
data.fillna("abc")

Unnamed: 0      Player's List Base Price          TYPE COST IN ₹ (CR.)  \
0             0        Shivam Mavi    4000000        BOWLER             6.0   
1             1      Joshua Little    5000000        BOWLER             4.4   
2             2    Kane Williamson   20000000       BATSMAN             2.0   
3             3        K.S. Bharat    2000000  WICKETKEEPER             1.2   
4             4       Mohit Sharma    5000000        BOWLER             0.5   
..          ...                ...        ...           ...             ...   
563         563        Dhruv Patel    2000000   ALL-ROUNDER             abc   
564         564    Jack Prestwidge    2000000   ALL-ROUNDER             abc   
565         565     Aditya Sarvate    2000000   ALL-ROUNDER             abc   
566         566      Sagar Solanki    2000000   ALL-ROUNDER             abc   
567         567  Prenelan Subrayen    2000000   ALL-ROUNDER             abc   

    Cost IN $ (000) 2022 Squad            Team  
0             720.0        KKR  Gujarat Titans  
1             528.0        abc  Gujarat Titans  
2             240.0        SRH  Gujarat Titans  
3             144.0         DC  Gujarat Titans  
4              60.0        abc  Gujarat Titans  
..              ...        ...             ...  
563             abc        abc          Unsold  
564             abc        abc          Unsold  
565             abc        abc          Unsold  
566             abc        abc          Unsold  
567             abc        abc          Unsold  

[568 rows x 8 columns]

In [ ]:
data.isnull().sum().sum()

988

In [ ]:
data=data.fillna("abc")

In [ ]:
data.isnull().sum().sum()

0

In [ ]:
data['TYPE'].value_counts()

TYPE
ALL-ROUNDER     213
BOWLER          189
BATSMAN          91
WICKETKEEPER     75
Name: count, dtype: int64

In [ ]:
data['Team'].unique()

array(['Gujarat Titans', 'Chennai Super Kings', 'Delhi Capitals',
       'Kolkata Knight Riders', 'Punjab Super Kings',
       'Lucknow Super Giants', 'Mumbai Indians',
       'Royal Challengers Banglore', 'Rajasthan Royals',
       'Sunrisers Hyderabad', 'Unsold'], dtype=object)

In [ ]:
data['Team'].nunique()

11

In [ ]:
data['Team']. value_counts()

Team
Unsold                        325
Gujarat Titans                 25
Chennai Super Kings            25
Delhi Capitals                 25
Lucknow Super Giants           25
Royal Challengers Banglore     25
Rajasthan Royals               25
Sunrisers Hyderabad            25
Mumbai Indians                 24
Kolkata Knight Riders          22
Punjab Super Kings             22
Name: count, dtype: int64

In [ ]:
data.sort_values(by='Team')

Unnamed: 0      Player's List Base Price         TYPE COST IN ₹ (CR.)  \
42           42       Devon Conway   Retained      BATSMAN             0.0   
26           26      Kyle Jamieson   10000000       BOWLER             1.0   
27           27     Nishant Sindhu    2000000  ALL-ROUNDER             0.6   
28           28     Ajinkya Rahane    5000000      BATSMAN             0.5   
29           29      Bhagath Varma    2000000  ALL-ROUNDER             0.2   
..          ...                ...        ...          ...             ...   
347         347    Richard Gleeson    5000000       BOWLER             abc   
346         346      Ben Dwarshuis    5000000       BOWLER             abc   
345         345    Sandeep Warrier    5000000  ALL-ROUNDER             abc   
363         363     Himanshu Bisht    2000000  ALL-ROUNDER             abc   
567         567  Prenelan Subrayen    2000000  ALL-ROUNDER             abc   

    Cost IN $ (000) 2022 Squad                 Team  
42              0.0        CSK  Chennai Super Kings  
26            120.0        abc  Chennai Super Kings  
27             72.0        abc  Chennai Super Kings  
28             60.0        KKR  Chennai Super Kings  
29             24.0        CSK  Chennai Super Kings  
..              ...        ...                  ...  
347             abc        abc               Unsold  
346             abc        abc               Unsold  
345             abc        abc               Unsold  
363             abc        abc               Unsold  
567             abc        abc               Unsold  

[568 rows x 8 columns]

In [ ]:
data.sort_values(by='Team',ascending=False)

Unnamed: 0   Player's List Base Price          TYPE COST IN ₹ (CR.)  \
284         284       Shai Hope   10000000  WICKETKEEPER             abc   
382         382     Vivek Singh    2000000  WICKETKEEPER             abc   
376         376      Robin Minz    2000000  WICKETKEEPER             abc   
377         377       Agniv Pan    2000000  WICKETKEEPER             abc   
378         378   Priyesh Patel    2000000  WICKETKEEPER             abc   
..          ...             ...        ...           ...             ...   
31           31   Shaik Rasheed    2000000       BATSMAN             0.2   
30           30     Ajay Mandal    2000000   ALL-ROUNDER             0.2   
29           29   Bhagath Varma    2000000   ALL-ROUNDER             0.2   
28           28  Ajinkya Rahane    5000000       BATSMAN             0.5   
26           26   Kyle Jamieson   10000000        BOWLER             1.0   

    Cost IN $ (000) 2022 Squad                 Team  
284             abc        abc               Unsold  
382             abc        abc               Unsold  
376             abc        abc               Unsold  
377             abc        abc               Unsold  
378             abc        abc               Unsold  
..              ...        ...                  ...  
31             24.0        abc  Chennai Super Kings  
30             24.0        abc  Chennai Super Kings  
29             24.0        CSK  Chennai Super Kings  
28             60.0        KKR  Chennai Super Kings  
26            120.0        abc  Chennai Super Kings  

[568 rows x 8 columns]

In [ ]:
data[["Player's List","Base Price","Team"]]
data[4:10]

Unnamed: 0    Player's List Base Price          TYPE COST IN ₹ (CR.)  \
4           4     Mohit Sharma    5000000        BOWLER             0.5   
5           5      Odean Smith    5000000   ALL-ROUNDER             0.5   
6           6      Urvil Patel    2000000  WICKETKEEPER             0.2   
7           7    Rahul Tewatia   Retained   ALL-ROUNDER             0.0   
8           8  Pradeep Sangwan   Retained   ALL-ROUNDER             0.0   
9           9      Rashid Khan   Retained        BOWLER             0.0   

  Cost IN $ (000) 2022 Squad            Team  
4            60.0        abc  Gujarat Titans  
5            60.0       PBKS  Gujarat Titans  
6            24.0        abc  Gujarat Titans  
7             0.0         GT  Gujarat Titans  
8             0.0         GT  Gujarat Titans  
9             0.0         GT  Gujarat Titans

In [ ]:
data.iloc[1:10,1:4]

Player's List Base Price          TYPE
1    Joshua Little    5000000        BOWLER
2  Kane Williamson   20000000       BATSMAN
3      K.S. Bharat    2000000  WICKETKEEPER
4     Mohit Sharma    5000000        BOWLER
5      Odean Smith    5000000   ALL-ROUNDER
6      Urvil Patel    2000000  WICKETKEEPER
7    Rahul Tewatia   Retained   ALL-ROUNDER
8  Pradeep Sangwan   Retained   ALL-ROUNDER
9      Rashid Khan   Retained        BOWLER

In [ ]:
import pandas as pd

In [ ]:
df=pd.read_csv('/content/market_fact.csv')
df

Ord_id  Prod_id   Ship_id    Cust_id      Sales  Discount  \
0     Ord_5446  Prod_16  SHP_7609  Cust_1818   136.8100      0.01   
1     Ord_5406  Prod_13  SHP_7549  Cust_1818    42.2700      0.01   
2     Ord_5446   Prod_4  SHP_7610  Cust_1818  4701.6900      0.00   
3     Ord_5456   Prod_6  SHP_7625  Cust_1818  2337.8900      0.09   
4     Ord_5485  Prod_17  SHP_7664  Cust_1818  4233.1500      0.08   
...        ...      ...       ...        ...        ...       ...   
8394  Ord_5353   Prod_4  SHP_7479  Cust_1798  2841.4395      0.08   
8395  Ord_5411   Prod_6  SHP_7555  Cust_1798   127.1600      0.10   
8396  Ord_5388   Prod_6  SHP_7524  Cust_1798   243.0500      0.02   
8397  Ord_5348  Prod_15  SHP_7469  Cust_1798  3872.8700      0.03   
8398  Ord_5459   Prod_6  SHP_7628  Cust_1798   603.6900      0.00   

      Order_Quantity   Profit  Shipping_Cost  Product_Base_Margin  
0                 23   -30.51           3.60                 0.56  
1                 13     4.56           0.93                 0.54  
2                 26  1148.90           2.50                 0.59  
3                 43   729.34          14.30                 0.37  
4                 35  1219.87          26.30                 0.38  
...              ...      ...            ...                  ...  
8394              28   374.63           7.69                 0.59  
8395              20   -74.03           6.92                 0.37  
8396              39   -70.85           5.35                 0.40  
8397              23   565.34          30.00                 0.62  
8398              47   131.39           4.86                 0.38  

[8399 rows x 10 columns]

In [ ]:
df.head()

Ord_id  Prod_id   Ship_id    Cust_id    Sales  Discount  Order_Quantity  \
0  Ord_5446  Prod_16  SHP_7609  Cust_1818   136.81      0.01              23   
1  Ord_5406  Prod_13  SHP_7549  Cust_1818    42.27      0.01              13   
2  Ord_5446   Prod_4  SHP_7610  Cust_1818  4701.69      0.00              26   
3  Ord_5456   Prod_6  SHP_7625  Cust_1818  2337.89      0.09              43   
4  Ord_5485  Prod_17  SHP_7664  Cust_1818  4233.15      0.08              35   

    Profit  Shipping_Cost  Product_Base_Margin  
0   -30.51           3.60                 0.56  
1     4.56           0.93                 0.54  
2  1148.90           2.50                 0.59  
3   729.34          14.30                 0.37  
4  1219.87          26.30                 0.38

In [ ]:
df.tail()

Ord_id  Prod_id   Ship_id    Cust_id      Sales  Discount  \
8394  Ord_5353   Prod_4  SHP_7479  Cust_1798  2841.4395      0.08   
8395  Ord_5411   Prod_6  SHP_7555  Cust_1798   127.1600      0.10   
8396  Ord_5388   Prod_6  SHP_7524  Cust_1798   243.0500      0.02   
8397  Ord_5348  Prod_15  SHP_7469  Cust_1798  3872.8700      0.03   
8398  Ord_5459   Prod_6  SHP_7628  Cust_1798   603.6900      0.00   

      Order_Quantity  Profit  Shipping_Cost  Product_Base_Margin  
8394              28  374.63           7.69                 0.59  
8395              20  -74.03           6.92                 0.37  
8396              39  -70.85           5.35                 0.40  
8397              23  565.34          30.00                 0.62  
8398              47  131.39           4.86                 0.38

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8399 entries, 0 to 8398
Data columns (total 10 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   Ord_id               8399 non-null   object 
 1   Prod_id              8399 non-null   object 
 2   Ship_id              8399 non-null   object 
 3   Cust_id              8399 non-null   object 
 4   Sales                8399 non-null   float64
 5   Discount             8399 non-null   float64
 6   Order_Quantity       8399 non-null   int64  
 7   Profit               8399 non-null   float64
 8   Shipping_Cost        8399 non-null   float64
 9   Product_Base_Margin  8336 non-null   float64
dtypes: float64(5), int64(1), object(4)
memory usage: 656.3+ KB


In [ ]:
df.isnull().sum()

Ord_id                  0
Prod_id                 0
Ship_id                 0
Cust_id                 0
Sales                   0
Discount                0
Order_Quantity          0
Profit                  0
Shipping_Cost           0
Product_Base_Margin    63
dtype: int64

In [ ]:
df.isnull()

Ord_id  Prod_id  Ship_id  Cust_id  Sales  Discount  Order_Quantity  \
0      False    False    False    False  False     False           False   
1      False    False    False    False  False     False           False   
2      False    False    False    False  False     False           False   
3      False    False    False    False  False     False           False   
4      False    False    False    False  False     False           False   
...      ...      ...      ...      ...    ...       ...             ...   
8394   False    False    False    False  False     False           False   
8395   False    False    False    False  False     False           False   
8396   False    False    False    False  False     False           False   
8397   False    False    False    False  False     False           False   
8398   False    False    False    False  False     False           False   

      Profit  Shipping_Cost  Product_Base_Margin  
0      False          False                False  
1      False          False                False  
2      False          False                False  
3      False          False                False  
4      False          False                False  
...      ...            ...                  ...  
8394   False          False                False  
8395   False          False                False  
8396   False          False                False  
8397   False          False                False  
8398   False          False                False  

[8399 rows x 10 columns]

In [ ]:
df.isnull().sum().sum()

63

In [ ]:
df.shape

(8399, 10)

In [ ]:
df.duplicated().sum()

0

In [ ]:
df.fillna("abc")

Ord_id  Prod_id   Ship_id    Cust_id      Sales  Discount  \
0     Ord_5446  Prod_16  SHP_7609  Cust_1818   136.8100      0.01   
1     Ord_5406  Prod_13  SHP_7549  Cust_1818    42.2700      0.01   
2     Ord_5446   Prod_4  SHP_7610  Cust_1818  4701.6900      0.00   
3     Ord_5456   Prod_6  SHP_7625  Cust_1818  2337.8900      0.09   
4     Ord_5485  Prod_17  SHP_7664  Cust_1818  4233.1500      0.08   
...        ...      ...       ...        ...        ...       ...   
8394  Ord_5353   Prod_4  SHP_7479  Cust_1798  2841.4395      0.08   
8395  Ord_5411   Prod_6  SHP_7555  Cust_1798   127.1600      0.10   
8396  Ord_5388   Prod_6  SHP_7524  Cust_1798   243.0500      0.02   
8397  Ord_5348  Prod_15  SHP_7469  Cust_1798  3872.8700      0.03   
8398  Ord_5459   Prod_6  SHP_7628  Cust_1798   603.6900      0.00   

      Order_Quantity   Profit  Shipping_Cost Product_Base_Margin  
0                 23   -30.51           3.60                0.56  
1                 13     4.56           0.93                0.54  
2                 26  1148.90           2.50                0.59  
3                 43   729.34          14.30                0.37  
4                 35  1219.87          26.30                0.38  
...              ...      ...            ...                 ...  
8394              28   374.63           7.69                0.59  
8395              20   -74.03           6.92                0.37  
8396              39   -70.85           5.35                 0.4  
8397              23   565.34          30.00                0.62  
8398              47   131.39           4.86                0.38  

[8399 rows x 10 columns]

In [ ]:
df.set_index('Ord_id')

Prod_id   Ship_id    Cust_id      Sales  Discount  Order_Quantity  \
Ord_id                                                                        
Ord_5446  Prod_16  SHP_7609  Cust_1818   136.8100      0.01              23   
Ord_5406  Prod_13  SHP_7549  Cust_1818    42.2700      0.01              13   
Ord_5446   Prod_4  SHP_7610  Cust_1818  4701.6900      0.00              26   
Ord_5456   Prod_6  SHP_7625  Cust_1818  2337.8900      0.09              43   
Ord_5485  Prod_17  SHP_7664  Cust_1818  4233.1500      0.08              35   
...           ...       ...        ...        ...       ...             ...   
Ord_5353   Prod_4  SHP_7479  Cust_1798  2841.4395      0.08              28   
Ord_5411   Prod_6  SHP_7555  Cust_1798   127.1600      0.10              20   
Ord_5388   Prod_6  SHP_7524  Cust_1798   243.0500      0.02              39   
Ord_5348  Prod_15  SHP_7469  Cust_1798  3872.8700      0.03              23   
Ord_5459   Prod_6  SHP_7628  Cust_1798   603.6900      0.00              47   

           Profit  Shipping_Cost Product_Base_Margin  
Ord_id                                                
Ord_5446   -30.51           3.60                0.56  
Ord_5406     4.56           0.93                0.54  
Ord_5446  1148.90           2.50                0.59  
Ord_5456   729.34          14.30                0.37  
Ord_5485  1219.87          26.30                0.38  
...           ...            ...                 ...  
Ord_5353   374.63           7.69                0.59  
Ord_5411   -74.03           6.92                0.37  
Ord_5388   -70.85           5.35                 0.4  
Ord_5348   565.34          30.00                0.62  
Ord_5459   131.39           4.86                0.38  

[8399 rows x 9 columns]

In [ ]:
df.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...  
8394    False
8395    False
8396    False
8397    False
8398    False
Length: 8399, dtype: bool

In [ ]:
df.describe()

Sales     Discount  Order_Quantity        Profit  Shipping_Cost
count   8399.000000  8399.000000     8399.000000   8399.000000    8399.000000
mean    1775.878179     0.049671       25.571735    181.184424      12.838557
std     3585.050525     0.031823       14.481071   1196.653371      17.264052
min        2.240000     0.000000        1.000000 -14140.700000       0.490000
25%      143.195000     0.020000       13.000000    -83.315000       3.300000
50%      449.420000     0.050000       26.000000     -1.500000       6.070000
75%     1709.320000     0.080000       38.000000    162.750000      13.990000
max    89061.050000     0.250000       50.000000  27220.690000     164.730000

In [ ]:
df.reset_index()

index    Ord_id  Prod_id   Ship_id    Cust_id      Sales  Discount  \
0         0  Ord_5446  Prod_16  SHP_7609  Cust_1818   136.8100      0.01   
1         1  Ord_5406  Prod_13  SHP_7549  Cust_1818    42.2700      0.01   
2         2  Ord_5446   Prod_4  SHP_7610  Cust_1818  4701.6900      0.00   
3         3  Ord_5456   Prod_6  SHP_7625  Cust_1818  2337.8900      0.09   
4         4  Ord_5485  Prod_17  SHP_7664  Cust_1818  4233.1500      0.08   
...     ...       ...      ...       ...        ...        ...       ...   
8394   8394  Ord_5353   Prod_4  SHP_7479  Cust_1798  2841.4395      0.08   
8395   8395  Ord_5411   Prod_6  SHP_7555  Cust_1798   127.1600      0.10   
8396   8396  Ord_5388   Prod_6  SHP_7524  Cust_1798   243.0500      0.02   
8397   8397  Ord_5348  Prod_15  SHP_7469  Cust_1798  3872.8700      0.03   
8398   8398  Ord_5459   Prod_6  SHP_7628  Cust_1798   603.6900      0.00   

      Order_Quantity   Profit  Shipping_Cost Product_Base_Margin  
0                 23   -30.51           3.60                0.56  
1                 13     4.56           0.93                0.54  
2                 26  1148.90           2.50                0.59  
3                 43   729.34          14.30                0.37  
4                 35  1219.87          26.30                0.38  
...              ...      ...            ...                 ...  
8394              28   374.63           7.69                0.59  
8395              20   -74.03           6.92                0.37  
8396              39   -70.85           5.35                 0.4  
8397              23   565.34          30.00                0.62  
8398              47   131.39           4.86                0.38  

[8399 rows x 11 columns]

In [ ]:
df.head()

Ord_id  Prod_id   Ship_id    Cust_id    Sales  Discount  Order_Quantity  \
0  Ord_5446  Prod_16  SHP_7609  Cust_1818   136.81      0.01              23   
1  Ord_5406  Prod_13  SHP_7549  Cust_1818    42.27      0.01              13   
2  Ord_5446   Prod_4  SHP_7610  Cust_1818  4701.69      0.00              26   
3  Ord_5456   Prod_6  SHP_7625  Cust_1818  2337.89      0.09              43   
4  Ord_5485  Prod_17  SHP_7664  Cust_1818  4233.15      0.08              35   

    Profit  Shipping_Cost Product_Base_Margin  
0   -30.51           3.60                0.56  
1     4.56           0.93                0.54  
2  1148.90           2.50                0.59  
3   729.34          14.30                0.37  
4  1219.87          26.30                0.38

In [ ]:
df.loc[2,'Sales']

4701.69

In [ ]:
df.loc[10:21,'Sales':'Profit']

Sales  Discount  Order_Quantity   Profit
10   4072.010      0.01              43  1675.98
11    465.900      0.05              38    79.34
12    305.050      0.04              27    23.12
13   3364.248      0.10              15  -693.23
14   1410.930      0.08              10  -317.48
15    460.690      0.06              48  -103.48
16    443.460      0.06              30   193.12
17  13255.930      0.02              25  4089.27
18    283.130      0.08              45  -141.26
19     41.970      0.05              12   -37.03
20     57.170      0.08              18   -24.03
21     81.250      0.01              11   -44.54

In [ ]:
df=df.set_index('Cust_id')

In [ ]:
df.loc[['Cust_1818','Cust_1641'],'Ship_id':'Profit']

Ship_id      Sales  Discount  Order_Quantity   Profit
Cust_id                                                          
Cust_1818  SHP_7609   136.8100      0.01              23   -30.51
Cust_1818  SHP_7549    42.2700      0.01              13     4.56
Cust_1818  SHP_7610  4701.6900      0.00              26  1148.90
Cust_1818  SHP_7625  2337.8900      0.09              43   729.34
Cust_1818  SHP_7664  4233.1500      0.08              35  1219.87
Cust_1818  SHP_7608   164.0200      0.03              23   -47.64
Cust_1641  SHP_6593  3410.1575      0.10              48  1137.91
Cust_1641  SHP_6593   162.0000      0.01              33    45.84
Cust_1641  SHP_6593    57.2200      0.07               8   -27.72
Cust_1641  SHP_6615  4072.0100      0.01              43  1675.98